# Develop the code to perform Naive Gauss Elimination.

$$Ax = b$$

$A$ is some square matrix.

$A = \begin{pmatrix}
a_{00} & a_{01} & a_{02}& a_{03}\\
a_{10} & a_{11} & a_{12}& a_{13}\\
a_{20} & a_{21} & a_{22}& a_{23}\\
a_{30} & a_{31} & a_{32}& a_{33}
\end{pmatrix}$

$x$ and $b$ are a column vectors.

$x = \begin{pmatrix}
x_0\\
x_1\\
x_2\\
x_3
\end{pmatrix}
$

$b = \begin{pmatrix}
b_0\\
b_1\\
b_2\\
b_3
\end{pmatrix}
$
## Start by developing the code to turn a matrix into Row-Echelon form: Foward-Elimation.

### Solve the system of equations - $x_1 , x_2 , x_3 , x_4$.

$x_1 + x_2 - 3x_3 + x_4 = 2$

$-5x_1 + 3x_2 - 4x_3 + x_4 = 0$

$x_1 + 0x_2 + 2x_3 - x_4 = 1$

$x_1 + 2x_2 + 0x_3 + 0x_4 = 12$

In [1]:
import numpy as np

#store the coeffients of a system of equations into list
#each list will represent a particular equation
eq1 = [1,1,-3,1]
eq2 = [-5,3,-4,1]
eq3 = [1,0,2,-1]
eq4 = [1,2,0,0]

A = np.array( [eq1, eq2 , eq3 , eq4], float ) #make an array out of the system of
                                              #equations
                                              #The A matrix

b = np.array( [2,0,1,12] , float ) #store the right-hand side of the equations into an
                                   #array

n = len(b)

A

array([[ 1.,  1., -3.,  1.],
       [-5.,  3., -4.,  1.],
       [ 1.,  0.,  2., -1.],
       [ 1.,  2.,  0.,  0.]])

## Remove $x_1$ from equation 2

Steps:

1) Multiply each element in equation 1 by $a_{10}/a_{00}$.

2) Then subtract equation 2 and $a_{10}/a_{00}$ * equation 1.

3) Store the result in equation 2.

In [2]:
factor = A[1,0] / A[0,0] #take the factor for the first equation
for i in range( 0 , n ): #need index numbers from 0 upto 3
  A[1,i] = A[1,i]  - factor * A[0,i] #multiply the factor to the first row. Then subtract the second row by the previous result

In [3]:
A

array([[  1.,   1.,  -3.,   1.],
       [  0.,   8., -19.,   6.],
       [  1.,   0.,   2.,  -1.],
       [  1.,   2.,   0.,   0.]])

## Remove all the $x_1$'s from equations 2 - 4. 

In [4]:
import numpy as np

#store the coeffients of a system of equations into list
#each list will represent a particular equation
eq1 = [1,1,-3,1]
eq2 = [-5,3,-4,1]
eq3 = [1,0,2,-1]
eq4 = [1,2,0,0]

A = np.array( [eq1, eq2 , eq3 , eq4], float ) #make an array out of the system of
                                              #equations
                                              #The A matrix

b = np.array( [2,0,1,12] , float ) #store the right-hand side of the equations into an
                                   #array
n = len(b)

A

array([[ 1.,  1., -3.,  1.],
       [-5.,  3., -4.,  1.],
       [ 1.,  0.,  2., -1.],
       [ 1.,  2.,  0.,  0.]])

### The factor will change for each equation.

Equation 1 will be mulitplied by $a_{10}/a_{00}$

Equation 2 will be mulitplied by $a_{20}/a_{00}$

Equation 3 will be mulitplied by $a_{30}/a_{00}$

### So in general to get rid of $x_1$, each equation will need to be multiplied by $a_{j0}/a_{00}$.

#### where $j = 1, 2, 3$.

##### **Note: We will also use the index number $j$ to represet all the different equations.**


In [5]:
for j in range( 1 , n ): #for each equation
  factor = A[j,0] / A[0,0] #take the factor for each equation
  for i in range( 0 , n ): #need index numbers from 0 upto n
    A[j,i] = A[j,i]  - factor * A[0,i] #R(j)= R(j) - factor * R(j-1)
  b[j] = b[j] - factor * b[0]

In [6]:
A

array([[  1.,   1.,  -3.,   1.],
       [  0.,   8., -19.,   6.],
       [  0.,  -1.,   5.,  -2.],
       [  0.,   1.,   3.,  -1.]])

In [7]:
b

array([ 2., 10., -1., 10.])

# Row Echelon form
## Remove all the $x_1$'s from equations 2 - 4. 
## Remove all the $x_2$'s from equations 3 and 4. 
## Remove $x_3$ from equation 4. 



### The factor will change for each equation and which variable we will be eliminating- $x_k$.

#### where $k = 1, 2, 3$.

### So in general to get rid of $x_k$, each equation will need to be multiplied by $a_{jk}/a_{kk}$.

#### where $j = 1, 2, 3$.

In [8]:
import numpy as np

#store the coeffients of a system of equations into list
#each list will represent a particular equation
eq1 = [1,1,-3,1]
eq2 = [-5,3,-4,1]
eq3 = [1,0,2,-1]
eq4 = [1,2,0,0]

A = np.array( [eq1, eq2 , eq3 , eq4], float ) #make an array out of the system of
                                              #equations
                                              #The A matrix

b = np.array( [2,0,1,12] , float ) #store the right-hand side of the equations into an
                                   #array
n = len(b)

A

array([[ 1.,  1., -3.,  1.],
       [-5.,  3., -4.,  1.],
       [ 1.,  0.,  2., -1.],
       [ 1.,  2.,  0.,  0.]])

In [9]:
for k in range( n - 1 ): #for each variable
  for j in range( k + 1 , n ): #for each equation
    factor = A[j,k] / A[k,k] #take the factor for each equation
    for i in range( k  , n ): #need index numbers from k+1 upto n
      A[j,i] = A[j,i]  - factor * A[k,i] #R(j)= R(j) - factor * R(j-1)
    b[j] = b[j] - factor * b[k]

In [10]:
A

array([[  1.        ,   1.        ,  -3.        ,   1.        ],
       [  0.        ,   8.        , -19.        ,   6.        ],
       [  0.        ,   0.        ,   2.625     ,  -1.25      ],
       [  0.        ,   0.        ,   0.        ,   0.80952381]])

In [11]:
b

array([ 2.        , 10.        ,  0.25      ,  8.23809524])

## Backward-Substitution

### Solve for $x_3$.

In [12]:
x = np.zeros(n) #array of zeros
x[3] = b[3]/A[3,3] #the last variable x(k) = b(k)/A[k,k]
x

array([ 0.        ,  0.        ,  0.        , 10.17647059])

### Solve for $x_2$.

In [13]:
sum_x3 = b[2]

x[2] = (sum_x3 - A[2,3]*x[3]) / A[2,2]

x

array([ 0.        ,  0.        ,  4.94117647, 10.17647059])

### Solve for $x_1$.

In [14]:
sum_x2 = b[1]
sum_x2 = sum_x2 - ( A[1,2]*x[2] + A[1,3]*x[3] )
x[1] = sum_x2 / A[1,1]

x

array([ 0.        ,  5.35294118,  4.94117647, 10.17647059])

### Solve for $x_0$.

In [15]:
sum_x1 = b[0]
sum_x1 = sum_x1 - ( A[0,1]*x[1] + A[0,2]*x[2] + A[0,3]*x[3] )
x[0] = sum_x1 / A[0,0]

x

array([ 1.29411765,  5.35294118,  4.94117647, 10.17647059])

### Solve for each $x_k$.

In [16]:
x = np.zeros(n) #array of zeros
x[n-1] = b[n-1]/A[n-1,n-1] #the last variable x(k) = b(k)/A[k,k]

for k in range( n - 2, -1 , -1 ): #for each b value
  s = b[k] #second to last b value
  for j in range( k + 1 , n ): #for each x1, x2,... x(k-2)
    s = s - A[k,j] * x[j]
  x[k] = s / A[k,k]

In [17]:
x

array([ 1.29411765,  5.35294118,  4.94117647, 10.17647059])

## Automate the task with a function

In [18]:
def Gauss( A , b ):
  #Foward-Elimation 
  n = len(b)

  for k in range( n - 1 ): #for each variable
    for j in range( k + 1 , n ): #for each equation
      factor = A[j,k] / A[k,k] #take the factor for each equation
      for i in range( k  , n ): #need index numbers from k+1 upto n
        A[j,i] = A[j,i]  - factor * A[k,i] #R(j)= R(j) - factor * R(j-1)
      b[j] = b[j] - factor * b[k]

  # Backward-Substitution
  x = np.zeros(n) #array of zeros to store solutions
  x[n-1] = b[n-1]/A[n-1,n-1] #the last variable x(k) = b(k)/A[k,k]

  for k in range( n - 2, -1 , -1 ): #for each b value
    s = b[k] #second to last b value
    for j in range( k + 1 , n ): #for each x1, x2,... x(k-2)
      s = s - A[k,j] * x[j]
    x[k] = s / A[k,k]

  return x

In [19]:
#store the coeffients of a system of equations into list
#each list will represent a particular equation
eq1 = [1,1,-3,1]
eq2 = [-5,3,-4,1]
eq3 = [1,0,2,-1]
eq4 = [1,2,0,0]

A = np.array( [eq1, eq2 , eq3 , eq4], float ) #make an array out of the system of
                                              #equations
                                              #The A matrix

b = np.array( [2,0,1,12] , float ) #store the right-hand side of the equations into an
                                   #array
Gauss(A,b)

array([ 1.29411765,  5.35294118,  4.94117647, 10.17647059])

##### **Note: This function does not perform partial pivoting**